[package]
name = "rcat"
version = "0.1.0"
authors = ["Andreas <andreas.ohman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
exitfailure = "0.5.1"
failure = "0.1.7"
